CREATE TABLE `marketplace_sectors` (
  `id` int NOT NULL AUTO_INCREMENT,
  `slug` varchar(80) NOT NULL,
  `labelAr` varchar(120) NOT NULL,
  `labelEn` varchar(120) NOT NULL,
  `labelFr` varchar(120) NOT NULL,
  `icon` varchar(40) NOT NULL DEFAULT 'store',
  `color` varchar(16) NOT NULL DEFAULT '#E76F3C',
  `descriptionAr` varchar(500),
  `descriptionEn` varchar(500),
  `descriptionFr` varchar(500),
  `sortOrder` int NOT NULL DEFAULT 0,
  `isActive` tinyint NOT NULL DEFAULT 1,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketplace_sectors_slug_unique` (`slug`),
  KEY `marketplace_sectors_slug_idx` (`slug`),
  KEY `marketplace_sectors_active_idx` (`isActive`, `sortOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `marketplace_listings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entity_id` varchar(30) NOT NULL,
  `sector_id` int NOT NULL,
  `restaurantId` int,
  `title` varchar(200) NOT NULL,
  `titleEn` varchar(200),
  `description` text,
  `descriptionEn` text,
  `imageUrl` varchar(500),
  `price` decimal(10,2) NOT NULL,
  `compareAtPrice` decimal(10,2),
  `currencyCode` varchar(3) NOT NULL DEFAULT 'SAR',
  `unit` varchar(40) NOT NULL DEFAULT 'piece',
  `stockQuantity` int,
  `status` enum('draft','active','paused','sold_out') NOT NULL DEFAULT 'draft',
  `isFeatured` tinyint NOT NULL DEFAULT 0,
  `sortOrder` int NOT NULL DEFAULT 0,
  `tagsJson` text,
  `metadataJson` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `marketplace_listings_entity_idx` (`entity_id`),
  KEY `marketplace_listings_sector_idx` (`sector_id`, `status`),
  KEY `marketplace_listings_restaurant_idx` (`restaurantId`),
  KEY `marketplace_listings_featured_idx` (`isFeatured`, `sortOrder`),
  CONSTRAINT `marketplace_listings_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`) ON DELETE CASCADE,
  CONSTRAINT `marketplace_listings_sector_fk` FOREIGN KEY (`sector_id`) REFERENCES `marketplace_sectors`(`id`),
  CONSTRAINT `marketplace_listings_restaurant_fk` FOREIGN KEY (`restaurantId`) REFERENCES `restaurants`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_referral_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entity_id` varchar(30) NOT NULL,
  `code` varchar(80) NOT NULL,
  `rewardType` enum('percent','fixed','points') NOT NULL DEFAULT 'percent',
  `rewardValue` decimal(10,2) NOT NULL DEFAULT 0,
  `maxUses` int,
  `useCount` int NOT NULL DEFAULT 0,
  `isActive` tinyint NOT NULL DEFAULT 1,
  `expiresAt` timestamp,
  `createdByUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `store_referral_links_code_unique` (`code`),
  KEY `store_referral_links_code_idx` (`code`),
  KEY `store_referral_links_entity_idx` (`entity_id`),
  CONSTRAINT `store_referral_links_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`) ON DELETE CASCADE,
  CONSTRAINT `store_referral_links_user_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_referral_records` (
  `id` int NOT NULL AUTO_INCREMENT,
  `linkId` int NOT NULL,
  `entity_id` varchar(30) NOT NULL,
  `referredUserId` int,
  `orderId` int,
  `status` enum('pending','converted','expired') NOT NULL DEFAULT 'pending',
  `rewardIssued` tinyint NOT NULL DEFAULT 0,
  `ipHash` varchar(64),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `convertedAt` timestamp,
  PRIMARY KEY (`id`),
  KEY `store_referral_records_link_idx` (`linkId`),
  KEY `store_referral_records_entity_idx` (`entity_id`),
  KEY `store_referral_records_status_idx` (`status`),
  CONSTRAINT `store_referral_records_link_fk` FOREIGN KEY (`linkId`) REFERENCES `store_referral_links`(`id`),
  CONSTRAINT `store_referral_records_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`),
  CONSTRAINT `store_referral_records_user_fk` FOREIGN KEY (`referredUserId`) REFERENCES `users`(`id`),
  CONSTRAINT `store_referral_records_order_fk` FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_coupons` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entity_id` varchar(30) NOT NULL,
  `code` varchar(64) NOT NULL,
  `description` varchar(300),
  `discountType` enum('percent','fixed') NOT NULL DEFAULT 'percent',
  `discountValue` decimal(10,2) NOT NULL,
  `minOrderAmount` decimal(10,2) NOT NULL DEFAULT 0,
  `maxDiscountAmount` decimal(10,2),
  `usageLimit` int,
  `perUserLimit` int NOT NULL DEFAULT 1,
  `useCount` int NOT NULL DEFAULT 0,
  `startsAt` timestamp,
  `endsAt` timestamp,
  `isActive` tinyint NOT NULL DEFAULT 1,
  `createdByUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `store_coupons_code_idx` (`code`),
  KEY `store_coupons_entity_idx` (`entity_id`),
  KEY `store_coupons_active_idx` (`entity_id`, `isActive`),
  CONSTRAINT `store_coupons_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`) ON DELETE CASCADE,
  CONSTRAINT `store_coupons_user_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_coupon_redemptions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `couponId` int NOT NULL,
  `entity_id` varchar(30) NOT NULL,
  `userId` int NOT NULL,
  `orderId` int,
  `discountApplied` decimal(10,2) NOT NULL,
  `redeemedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `store_coupon_redemptions_coupon_idx` (`couponId`),
  KEY `store_coupon_redemptions_user_idx` (`userId`, `couponId`),
  CONSTRAINT `store_coupon_redemptions_coupon_fk` FOREIGN KEY (`couponId`) REFERENCES `store_coupons`(`id`),
  CONSTRAINT `store_coupon_redemptions_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`),
  CONSTRAINT `store_coupon_redemptions_user_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`),
  CONSTRAINT `store_coupon_redemptions_order_fk` FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_campaigns` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entity_id` varchar(30) NOT NULL,
  `name` varchar(160) NOT NULL,
  `description` text,
  `type` enum('general','seasonal','referral_boost','loyalty_boost','flash_sale') NOT NULL DEFAULT 'general',
  `status` enum('draft','scheduled','active','ended') NOT NULL DEFAULT 'draft',
  `startsAt` timestamp,
  `endsAt` timestamp,
  `bonusPoints` int DEFAULT 0,
  `bonusPercent` decimal(5,2) DEFAULT 0,
  `targetCouponId` int,
  `createdByUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `store_campaigns_entity_idx` (`entity_id`, `status`),
  CONSTRAINT `store_campaigns_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`) ON DELETE CASCADE,
  CONSTRAINT `store_campaigns_coupon_fk` FOREIGN KEY (`targetCouponId`) REFERENCES `store_coupons`(`id`),
  CONSTRAINT `store_campaigns_user_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_loyalty_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entity_id` varchar(30) NOT NULL,
  `pointsPerCurrency` decimal(5,2) NOT NULL DEFAULT 1.00,
  `redeemRate` decimal(5,2) NOT NULL DEFAULT 0.01,
  `minPointsToRedeem` int NOT NULL DEFAULT 100,
  `welcomeBonusPoints` int NOT NULL DEFAULT 0,
  `tierThresholdsJson` text,
  `isActive` tinyint NOT NULL DEFAULT 1,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `store_loyalty_settings_entity_unique` (`entity_id`),
  KEY `store_loyalty_settings_entity_idx` (`entity_id`),
  CONSTRAINT `store_loyalty_settings_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_loyalty_accounts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entity_id` varchar(30) NOT NULL,
  `userId` int NOT NULL,
  `pointsBalance` int NOT NULL DEFAULT 0,
  `tier` varchar(40) NOT NULL DEFAULT 'standard',
  `totalEarned` int NOT NULL DEFAULT 0,
  `totalRedeemed` int NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `store_loyalty_accounts_entity_user_unique` (`entity_id`, `userId`),
  CONSTRAINT `store_loyalty_accounts_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`),
  CONSTRAINT `store_loyalty_accounts_user_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_reward_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entity_id` varchar(30) NOT NULL,
  `userId` int NOT NULL,
  `type` enum('earn','redeem','adjust','expire','welcome') NOT NULL,
  `points` int NOT NULL,
  `balanceAfter` int NOT NULL DEFAULT 0,
  `referenceType` varchar(60),
  `referenceId` int,
  `note` varchar(300),
  `createdByUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `store_reward_tx_entity_user_idx` (`entity_id`, `userId`),
  KEY `store_reward_tx_type_idx` (`type`, `createdAt`),
  CONSTRAINT `store_reward_tx_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`),
  CONSTRAINT `store_reward_tx_user_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`),
  CONSTRAINT `store_reward_tx_createdby_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `affiliate_accounts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `code` varchar(80) NOT NULL,
  `commissionRate` decimal(5,2) NOT NULL DEFAULT 5.00,
  `totalEarnings` decimal(12,2) NOT NULL DEFAULT 0.00,
  `paidEarnings` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` enum('pending','active','suspended','rejected') NOT NULL DEFAULT 'pending',
  `appliedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approvedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `affiliate_accounts_code_unique` (`code`),
  KEY `affiliate_accounts_user_idx` (`userId`),
  KEY `affiliate_accounts_code_idx` (`code`),
  CONSTRAINT `affiliate_accounts_user_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `affiliate_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `affiliateUserId` int NOT NULL,
  `entity_id` varchar(30),
  `code` varchar(80) NOT NULL,
  `targetPath` varchar(300) NOT NULL DEFAULT '/',
  `clickCount` int NOT NULL DEFAULT 0,
  `conversionCount` int NOT NULL DEFAULT 0,
  `isActive` tinyint NOT NULL DEFAULT 1,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `affiliate_links_code_unique` (`code`),
  KEY `affiliate_links_code_idx` (`code`),
  KEY `affiliate_links_affiliate_idx` (`affiliateUserId`),
  KEY `affiliate_links_entity_idx` (`entity_id`),
  CONSTRAINT `affiliate_links_affiliate_fk` FOREIGN KEY (`affiliateUserId`) REFERENCES `affiliate_accounts`(`id`),
  CONSTRAINT `affiliate_links_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `affiliate_commissions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `affiliateUserId` int NOT NULL,
  `linkId` int,
  `entity_id` varchar(30),
  `orderId` int,
  `orderAmount` decimal(12,2) NOT NULL,
  `commissionRate` decimal(5,2) NOT NULL,
  `commissionAmount` decimal(12,2) NOT NULL,
  `status` enum('pending','approved','paid','rejected') NOT NULL DEFAULT 'pending',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approvedAt` timestamp,
  PRIMARY KEY (`id`),
  KEY `affiliate_commissions_affiliate_idx` (`affiliateUserId`),
  KEY `affiliate_commissions_status_idx` (`status`),
  CONSTRAINT `affiliate_commissions_affiliate_fk` FOREIGN KEY (`affiliateUserId`) REFERENCES `affiliate_accounts`(`id`),
  CONSTRAINT `affiliate_commissions_link_fk` FOREIGN KEY (`linkId`) REFERENCES `affiliate_links`(`id`),
  CONSTRAINT `affiliate_commissions_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `platform_entities`(`id`),
  CONSTRAINT `affiliate_commissions_order_fk` FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `affiliate_payout_requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `affiliateUserId` int NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `currencyCode` varchar(3) NOT NULL DEFAULT 'SAR',
  `paymentMethod` varchar(40) NOT NULL DEFAULT 'bank_transfer',
  `paymentDetailsJson` text,
  `status` enum('pending','processing','completed','rejected') NOT NULL DEFAULT 'pending',
  `reviewNote` varchar(500),
  `reviewedByUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processedAt` timestamp,
  PRIMARY KEY (`id`),
  KEY `affiliate_payouts_affiliate_idx` (`affiliateUserId`),
  KEY `affiliate_payouts_status_idx` (`status`),
  CONSTRAINT `affiliate_payouts_affiliate_fk` FOREIGN KEY (`affiliateUserId`) REFERENCES `affiliate_accounts`(`id`),
  CONSTRAINT `affiliate_payouts_reviewer_fk` FOREIGN KEY (`reviewedByUserId`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed marketplace sectors from existing platform sectors + new ones
INSERT INTO `marketplace_sectors` (`slug`, `labelAr`, `labelEn`, `labelFr`, `icon`, `color`, `sortOrder`, `isActive`) VALUES
('restaurant', 'مطاعم', 'Restaurants', 'Restaurants', 'utensils', '#E76F3C', 1, 1),
('vegetables', 'خضروات', 'Vegetables', 'Légumes', 'leaf', '#22c55e', 2, 1),
('grocery', 'بقالة', 'Grocery', 'Épicerie', 'shopping-cart', '#3b82f6', 3, 1),
('laundry', 'غسيل', 'Laundry', 'Blanchisserie', 'shirt', '#8b5cf6', 4, 1),
('automotive', 'سيارات', 'Automotive', 'Automobile', 'car', '#ef4444', 5, 1),
('beauty_salon', 'صالون تجميل', 'Beauty Salon', 'Salon de Beauté', 'scissors', '#ec4899', 6, 1),
('public_works', 'أعمال عامة', 'Public Works', 'Travaux Publics', 'hard-hat', '#f59e0b', 7, 1),
('fashion', 'أزياء', 'Fashion', 'Mode', 'tshirt', '#06b6d4', 8, 1),
('sweets', 'حلويات', 'Sweets', 'Confiseries', 'cake', '#d946ef', 9, 1),
('electronics', 'إلكترونيات', 'Electronics', 'Électronique', 'laptop', '#64748b', 10, 1),
('health', 'صحة وعلاج', 'Health & Wellness', 'Santé', 'heart-pulse', '#10b981', 11, 1),
('home_services', 'خدمات منزلية', 'Home Services', 'Services à Domicile', 'home', '#f97316', 12, 1),
('education', 'تعليم', 'Education', 'Éducation', 'graduation-cap', '#6366f1', 13, 1),
('flowers', 'ورود و هدايا', 'Flowers & Gifts', 'Fleurs & Cadeaux', 'flower', '#f43f5e', 14, 1),
('pets', 'حيوانات أليفة', 'Pets', 'Animaux de Compagnie', 'paw', '#a855f7', 15, 1);
