import { Car, CookingPot, Flower2, WashingMachine, Wrench, Search, ShoppingBag, ShoppingBasket, Sparkles, Store, UtensilsCrossed, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useLanguage } from "@/contexts/LanguageContext";

type FallbackSector = { slug: string; labelAr: string; labelEn: string; labelFr: string; icon: LucideIcon; color: string; listingCount: number };
const fallbackSectors: FallbackSector[] = [
  { slug: "restaurants-food-cafes", labelAr: "المطاعم والمأكولات والمقاهي", labelEn: "Restaurants, Food & Cafes", labelFr: "Restaurants, cuisine et cafés", icon: UtensilsCrossed, color: "#f97316", listingCount: 0 },
  { slug: "fashion-apparel", labelAr: "الموضة والأزياء والملبوسات", labelEn: "Fashion, Clothing & Apparel", labelFr: "Mode et habillement", icon: ShoppingBag, color: "#db2777", listingCount: 0 },
  { slug: "beauty-salons", labelAr: "الصالونات والتجميل والحلاقة", labelEn: "Beauty, Salons & Barbers", labelFr: "Beauté, salons et coiffure", icon: Flower2, color: "#8b5cf6", listingCount: 0 },
  { slug: "groceries-hypermarkets", labelAr: "البقالات والتموينات والهايبرماركت", labelEn: "Groceries & Hypermarkets", labelFr: "Épiceries et hypermarchés", icon: ShoppingBasket, color: "#0ea5e9", listingCount: 0 },
  { slug: "fresh-produce", labelAr: "الخضار والفواكه والتمور والمنتجات الطازجة", labelEn: "Fresh Produce, Fruits & Dates", labelFr: "Produits frais, fruits et dattes", icon: CookingPot, color: "#22c55e", listingCount: 0 },
  { slug: "laundry-rug-care", labelAr: "مغاسل الملابس والسجاد والعناية", labelEn: "Laundry, Rug & Care", labelFr: "Laverie, tapis et entretien", icon: WashingMachine, color: "#6366f1", listingCount: 0 },
  { slug: "automotive", labelAr: "خدمات السيارات والصيانة ومغاسل السيارات", labelEn: "Automotive, Repair & Car Wash", labelFr: "Auto, réparation et lavage", icon: Car, color: "#ef4444", listingCount: 0 },
  { slug: "field-services", labelAr: "الأشغال العامة والصيانة المنزلية والخدمات الميدانية", labelEn: "Field Services & Home Maintenance", labelFr: "Services terrain et maintenance", icon: Wrench, color: "#eab308", listingCount: 0 },
];

export default function MarketplaceLanding() {
  const { language, direction } = useLanguage();
  const [search, setSearch] = useState("");
  const sectorsQuery = trpc.marketplace.publicSectors.useQuery(undefined, { retry: false });
  const storesQuery = trpc.marketplace.publicStores.useQuery({ search: search.trim() || undefined }, { retry: false });
  const liveSectors = sectorsQuery.data ?? [];
  const rows = liveSectors.length ? liveSectors.map((sector) => ({ ...sector, icon: fallbackSectors.find((item) => item.slug === sector.slug)?.icon ?? Store })) : fallbackSectors;
  const query = search.trim().toLowerCase();
  const visibleSectors = query ? rows.filter((sector) => `${sector.labelAr} ${sector.labelEn} ${sector.labelFr}`.toLowerCase().includes(query)) : rows;
  const label = (sector: typeof visibleSectors[number]) => language === "ar" ? sector.labelAr : language === "fr" ? sector.labelFr : sector.labelEn;
  const copy = language === "ar" ? { subtitle: "سوق متعدد القطاعات", title: "سوق NFOOD لكل المتاجر والخدمات", body: "تصفّح القطاعات والمتاجر من واجهة واحدة، ثم انتقل مباشرة إلى المنتجات والخدمات المتاحة.", search: "ابحث عن متجر أو منتج أو قطاع...", merchant: "لوحة التاجر", affiliate: "التسويق بالعمولة", home: "الرئيسية", sectors: "القطاعات", stores: "المتاجر النشطة", explore: "استكشف القطاع" } : language === "fr" ? { subtitle: "Marché multi-secteurs", title: "Le marché NFOOD des boutiques et services", body: "Parcourez les secteurs et boutiques depuis une seule interface.", search: "Rechercher une boutique, un produit ou un secteur...", merchant: "Espace marchand", affiliate: "Affiliation", home: "Accueil", sectors: "Secteurs", stores: "Boutiques actives", explore: "Découvrir" } : { subtitle: "Multi-sector marketplace", title: "NFOOD Marketplace for stores and services", body: "Browse sectors and active stores from one focused experience.", search: "Search stores, products, or sectors...", merchant: "Merchant console", affiliate: "Affiliate", home: "Home", sectors: "Sectors", stores: "Active stores", explore: "Explore" };

  return <main dir={direction} className="min-h-screen bg-[#0b0f17] text-white">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#0b0f17]/90 px-5 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#E76F3C] text-lg font-black text-white">N</span><span><strong className="block tracking-[.15em]">NFOOD MARKETPLACE</strong><small className="block text-[10px] font-bold tracking-[.2em] text-orange-300/80">{copy.subtitle}</small></span></Link><nav className="flex flex-wrap items-center gap-4 text-sm font-bold text-slate-300"><Link href="/affiliate" className="hover:text-white">{copy.affiliate}</Link><Link href="/store-marketing" className="hover:text-white">{copy.merchant}</Link><Link href="/" className="rounded-xl border border-white/15 px-4 py-2 hover:bg-white/10">{copy.home}</Link></nav></div></header>
    <section className="relative isolate overflow-hidden px-5 py-14 md:px-8"><div className="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-orange-500/20 blur-3xl" /><div className="relative mx-auto max-w-7xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-orange-300/30 bg-orange-400/10 px-3 py-2 text-xs font-bold text-orange-200"><Sparkles className="h-4 w-4" /> {copy.subtitle}</div><h1 className="max-w-4xl text-4xl font-black leading-tight md:text-6xl">{copy.title}</h1><p className="mt-5 max-w-2xl leading-8 text-slate-300">{copy.body}</p><div className="relative mt-7 max-w-xl"><Search className="pointer-events-none absolute right-4 top-3 h-5 w-5 text-slate-500" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={copy.search} className="h-12 rounded-2xl border-white/10 bg-white/5 pr-12 text-white placeholder:text-slate-500" /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-20 md:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-orange-300">Trend Kitchen · Market</p><h2 className="mt-2 text-2xl font-black">{copy.sectors}</h2></div><span className="text-sm font-bold text-slate-400">{visibleSectors.length}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visibleSectors.map((sector) => { const Icon = sector.icon; return <Link key={sector.slug} href={`/marketplace/sector/${sector.slug}`} className="group overflow-hidden rounded-3xl border border-white/10 bg-white/5 transition hover:-translate-y-1 hover:border-orange-400/40 hover:bg-white/10"><div className="flex h-28 items-end justify-between p-5" style={{ background: `linear-gradient(135deg, ${sector.color}bb, #111827)` }}><span className="rounded-full bg-black/20 px-3 py-1 text-[11px] font-bold text-white">{sector.listingCount} {language === "ar" ? "عنصر" : "items"}</span><Icon className="h-8 w-8 text-white" /></div><div className="p-5"><h3 className="min-h-12 font-black leading-6">{label(sector)}</h3><span className="mt-4 inline-flex text-xs font-bold text-orange-300">{copy.explore}</span></div></Link>; })}</div>
      <div className="mt-16"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-emerald-300">NFOOD</p><h2 className="mt-2 text-2xl font-black">{copy.stores}</h2></div></div>{storesQuery.isLoading ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map((item) => <div key={item} className="h-48 animate-pulse rounded-3xl border border-white/10 bg-white/5" />)}</div> : (storesQuery.data ?? []).length === 0 ? <div className="mt-6 rounded-3xl border border-dashed border-white/15 p-12 text-center text-sm text-slate-400">{language === "ar" ? "لا توجد متاجر منشورة بمحتوى بعد." : language === "fr" ? "Aucune boutique publiée pour le moment." : "No published stores yet."}</div> : <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(storesQuery.data ?? []).map((store) => <Link key={store.entityId} href={`/store/${store.entityId}`} className="overflow-hidden rounded-3xl border border-white/10 bg-white/5 transition hover:-translate-y-1 hover:border-orange-400/40"><div className="h-24 p-4" style={{ background: `linear-gradient(135deg, ${store.restaurant?.brandColor ?? "#162033"}, ${store.restaurant?.brandAccentColor ?? "#334155"})` }} /><div className="p-5"><h3 className="font-black">{store.customerName}</h3><p className="mt-2 text-xs text-slate-400">{store.listingCount} {language === "ar" ? "منتجًا أو خدمة" : "listings"}</p></div></Link>)}</div>}</div>
    </section>
  </main>;
}
