export type CurrencyDefinition = {
  code: string;
  name: string;
  nameAr: string;
  symbol: string;
  decimals: number;
  symbolPosition: "before" | "after";
};

export type CountryDefinition = {
  code: string;
  name: string;
  nameAr: string;
  currencyCode: string;
  locale: string;
};

export const CURRENCIES: readonly CurrencyDefinition[] = [
  { code: "SAR", name: "Saudi Riyal", nameAr: "الريال السعودي", symbol: "ر.س", decimals: 2, symbolPosition: "after" },
  { code: "AED", name: "UAE Dirham", nameAr: "الدرهم الإماراتي", symbol: "د.إ", decimals: 2, symbolPosition: "after" },
  { code: "KWD", name: "Kuwaiti Dinar", nameAr: "الدينار الكويتي", symbol: "د.ك", decimals: 3, symbolPosition: "after" },
  { code: "QAR", name: "Qatari Riyal", nameAr: "الريال القطري", symbol: "ر.ق", decimals: 2, symbolPosition: "after" },
  { code: "BHD", name: "Bahraini Dinar", nameAr: "الدينار البحريني", symbol: "د.ب", decimals: 3, symbolPosition: "after" },
  { code: "OMR", name: "Omani Rial", nameAr: "الريال العماني", symbol: "ر.ع", decimals: 3, symbolPosition: "after" },
  { code: "JOD", name: "Jordanian Dinar", nameAr: "الدينار الأردني", symbol: "د.أ", decimals: 3, symbolPosition: "after" },
  { code: "EGP", name: "Egyptian Pound", nameAr: "الجنيه المصري", symbol: "ج.م", decimals: 2, symbolPosition: "after" },
  { code: "DZD", name: "Algerian Dinar", nameAr: "الدينار الجزائري", symbol: "دج", decimals: 2, symbolPosition: "after" },
  { code: "AOA", name: "Angolan Kwanza", nameAr: "الكوانزا الأنغولي", symbol: "Kz", decimals: 2, symbolPosition: "after" },
  { code: "BWP", name: "Botswana Pula", nameAr: "البولا البوتسواني", symbol: "P", decimals: 2, symbolPosition: "after" },
  { code: "BIF", name: "Burundian Franc", nameAr: "الفرنك البوروندي", symbol: "FBu", decimals: 0, symbolPosition: "after" },
  { code: "CVE", name: "Cape Verdean Escudo", nameAr: "الإسكودو الرأس أخضري", symbol: "$", decimals: 2, symbolPosition: "after" },
  { code: "XAF", name: "Central African CFA Franc", nameAr: "فرنك وسط أفريقيا", symbol: "FCFA", decimals: 0, symbolPosition: "after" },
  { code: "XOF", name: "West African CFA Franc", nameAr: "فرنك غرب أفريقيا", symbol: "F CFA", decimals: 0, symbolPosition: "after" },
  { code: "KMF", name: "Comorian Franc", nameAr: "الفرنك القمري", symbol: "CF", decimals: 0, symbolPosition: "after" },
  { code: "CDF", name: "Congolese Franc", nameAr: "الفرنك الكونغولي", symbol: "FC", decimals: 2, symbolPosition: "after" },
  { code: "DJF", name: "Djiboutian Franc", nameAr: "الفرنك الجيبوتي", symbol: "Fdj", decimals: 0, symbolPosition: "after" },
  { code: "ERN", name: "Eritrean Nakfa", nameAr: "الناكفا الإريترية", symbol: "Nfk", decimals: 2, symbolPosition: "after" },
  { code: "SZL", name: "Eswatini Lilangeni", nameAr: "الليلانجيني الإسواتيني", symbol: "E", decimals: 2, symbolPosition: "after" },
  { code: "ETB", name: "Ethiopian Birr", nameAr: "البِر الإثيوبي", symbol: "Br", decimals: 2, symbolPosition: "after" },
  { code: "GMD", name: "Gambian Dalasi", nameAr: "الدالاسي الغامبي", symbol: "D", decimals: 2, symbolPosition: "after" },
  { code: "GHS", name: "Ghanaian Cedi", nameAr: "السيدي الغاني", symbol: "GH₵", decimals: 2, symbolPosition: "after" },
  { code: "GNF", name: "Guinean Franc", nameAr: "الفرنك الغيني", symbol: "FG", decimals: 0, symbolPosition: "after" },
  { code: "KES", name: "Kenyan Shilling", nameAr: "الشلن الكيني", symbol: "KSh", decimals: 2, symbolPosition: "after" },
  { code: "LSL", name: "Lesotho Loti", nameAr: "اللوتي الليسوتي", symbol: "L", decimals: 2, symbolPosition: "after" },
  { code: "LRD", name: "Liberian Dollar", nameAr: "الدولار الليبيري", symbol: "$", decimals: 2, symbolPosition: "after" },
  { code: "LYD", name: "Libyan Dinar", nameAr: "الدينار الليبي", symbol: "ل.د", decimals: 3, symbolPosition: "after" },
  { code: "MGA", name: "Malagasy Ariary", nameAr: "الأرياري الملغاشي", symbol: "Ar", decimals: 2, symbolPosition: "after" },
  { code: "MWK", name: "Malawian Kwacha", nameAr: "الكواشا الملاوي", symbol: "MK", decimals: 2, symbolPosition: "after" },
  { code: "MRU", name: "Mauritanian Ouguiya", nameAr: "الأوقية الموريتانية", symbol: "UM", decimals: 2, symbolPosition: "after" },
  { code: "MUR", name: "Mauritian Rupee", nameAr: "الروبية الموريشية", symbol: "₨", decimals: 2, symbolPosition: "after" },
  { code: "MAD", name: "Moroccan Dirham", nameAr: "الدرهم المغربي", symbol: "د.م", decimals: 2, symbolPosition: "after" },
  { code: "MZN", name: "Mozambican Metical", nameAr: "المتكال الموزمبيقي", symbol: "MT", decimals: 2, symbolPosition: "after" },
  { code: "NAD", name: "Namibian Dollar", nameAr: "الدولار الناميبي", symbol: "$", decimals: 2, symbolPosition: "after" },
  { code: "NGN", name: "Nigerian Naira", nameAr: "النايرا النيجيرية", symbol: "₦", decimals: 2, symbolPosition: "after" },
  { code: "RWF", name: "Rwandan Franc", nameAr: "الفرنك الرواندي", symbol: "FRw", decimals: 0, symbolPosition: "after" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", nameAr: "الدوبرا الساوتومية", symbol: "Db", decimals: 2, symbolPosition: "after" },
  { code: "SCR", name: "Seychellois Rupee", nameAr: "الروبية السيشلية", symbol: "₨", decimals: 2, symbolPosition: "after" },
  { code: "SLE", name: "Sierra Leonean Leone", nameAr: "الليون السيراليوني", symbol: "Le", decimals: 2, symbolPosition: "after" },
  { code: "SOS", name: "Somali Shilling", nameAr: "الشلن الصومالي", symbol: "Sh", decimals: 2, symbolPosition: "after" },
  { code: "SSP", name: "South Sudanese Pound", nameAr: "الجنيه الجنوب سوداني", symbol: "£", decimals: 2, symbolPosition: "after" },
  { code: "SDG", name: "Sudanese Pound", nameAr: "الجنيه السوداني", symbol: "ج.س.", decimals: 2, symbolPosition: "after" },
  { code: "TZS", name: "Tanzanian Shilling", nameAr: "الشلن التنزاني", symbol: "TSh", decimals: 2, symbolPosition: "after" },
  { code: "TND", name: "Tunisian Dinar", nameAr: "الدينار التونسي", symbol: "د.ت", decimals: 3, symbolPosition: "after" },
  { code: "UGX", name: "Ugandan Shilling", nameAr: "الشلن الأوغندي", symbol: "USh", decimals: 0, symbolPosition: "after" },
  { code: "ZMW", name: "Zambian Kwacha", nameAr: "الكواشا الزامبي", symbol: "ZK", decimals: 2, symbolPosition: "after" },
  { code: "ZWL", name: "Zimbabwean Dollar", nameAr: "الدولار الزيمبابوي", symbol: "$", decimals: 2, symbolPosition: "after" },
  { code: "ZAR", name: "South African Rand", nameAr: "الراند الجنوب أفريقي", symbol: "R", decimals: 2, symbolPosition: "after" },
  { code: "TRY", name: "Turkish Lira", nameAr: "الليرة التركية", symbol: "₺", decimals: 2, symbolPosition: "after" },
  { code: "USD", name: "US Dollar", nameAr: "الدولار الأمريكي", symbol: "$", decimals: 2, symbolPosition: "before" },
  { code: "EUR", name: "Euro", nameAr: "اليورو", symbol: "€", decimals: 2, symbolPosition: "before" },
  { code: "GBP", name: "British Pound", nameAr: "الجنيه الإسترليني", symbol: "£", decimals: 2, symbolPosition: "before" },
  { code: "CAD", name: "Canadian Dollar", nameAr: "الدولار الكندي", symbol: "CA$", decimals: 2, symbolPosition: "before" },
  { code: "AUD", name: "Australian Dollar", nameAr: "الدولار الأسترالي", symbol: "A$", decimals: 2, symbolPosition: "before" },
  { code: "INR", name: "Indian Rupee", nameAr: "الروبية الهندية", symbol: "₹", decimals: 2, symbolPosition: "before" },
  { code: "PKR", name: "Pakistani Rupee", nameAr: "الروبية الباكستانية", symbol: "₨", decimals: 2, symbolPosition: "after" },
  { code: "AFN", name: "Afghan Afghani", nameAr: "أفغاني أفغاني", symbol: "؋", decimals: 2, symbolPosition: "after" },
  { code: "ALL", name: "Albanian Lek", nameAr: "ليك ألباني", symbol: "L", decimals: 2, symbolPosition: "after" },
  { code: "AMD", name: "Armenian Dram", nameAr: "درام أرمني", symbol: "֏", decimals: 2, symbolPosition: "before" },
  { code: "ARS", name: "Argentine Peso", nameAr: "بيزو أرجنتيني", symbol: "ARS$", decimals: 2, symbolPosition: "before" },
  { code: "AZN", name: "Azerbaijani Manat", nameAr: "مانات أذربيجاني", symbol: "₼", decimals: 2, symbolPosition: "before" },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark", nameAr: "مارك بوسني", symbol: "KM", decimals: 2, symbolPosition: "after" },
  { code: "BBD", name: "Barbadian Dollar", nameAr: "دولار باربادوسي", symbol: "Bds$", decimals: 2, symbolPosition: "before" },
  { code: "BDT", name: "Bangladeshi Taka", nameAr: "تاكا بنغلاديشي", symbol: "৳", decimals: 2, symbolPosition: "before" },
  { code: "BGN", name: "Bulgarian Lev", nameAr: "ليف بلغاري", symbol: "лв", decimals: 2, symbolPosition: "after" },
  { code: "BND", name: "Brunei Dollar", nameAr: "دولار بروناي", symbol: "B$", decimals: 2, symbolPosition: "before" },
  { code: "BOB", name: "Bolivian Boliviano", nameAr: "بوليفيانو بوليفي", symbol: "Bs", decimals: 2, symbolPosition: "before" },
  { code: "BRL", name: "Brazilian Real", nameAr: "ريال برازيلي", symbol: "R$", decimals: 2, symbolPosition: "before" },
  { code: "BSD", name: "Bahamian Dollar", nameAr: "دولار باهامي", symbol: "B$", decimals: 2, symbolPosition: "before" },
  { code: "BTN", name: "Bhutanese Ngultrum", nameAr: "نغولترم بوتاني", symbol: "Nu.", decimals: 2, symbolPosition: "before" },
  { code: "BYN", name: "Belarusian Ruble", nameAr: "روبل بيلاروسي", symbol: "Br", decimals: 2, symbolPosition: "before" },
  { code: "BZD", name: "Belize Dollar", nameAr: "دولار بليزي", symbol: "BZ$", decimals: 2, symbolPosition: "before" },
  { code: "CHF", name: "Swiss Franc", nameAr: "فرنك سويسري", symbol: "CHF", decimals: 2, symbolPosition: "before" },
  { code: "CLP", name: "Chilean Peso", nameAr: "بيزو تشيلي", symbol: "CLP$", decimals: 0, symbolPosition: "before" },
  { code: "CNY", name: "Chinese Yuan", nameAr: "يوان صيني", symbol: "¥", decimals: 2, symbolPosition: "before" },
  { code: "COP", name: "Colombian Peso", nameAr: "بيزو كولومبي", symbol: "COP$", decimals: 2, symbolPosition: "before" },
  { code: "CRC", name: "Costa Rican Colón", nameAr: "كولون كوستاريكي", symbol: "₡", decimals: 2, symbolPosition: "before" },
  { code: "CUP", name: "Cuban Peso", nameAr: "بيزو كوبي", symbol: "$", decimals: 2, symbolPosition: "before" },
  { code: "CZK", name: "Czech Koruna", nameAr: "كورونة تشيكية", symbol: "Kč", decimals: 2, symbolPosition: "after" },
  { code: "DKK", name: "Danish Krone", nameAr: "كرونة دنماركية", symbol: "kr", decimals: 2, symbolPosition: "after" },
  { code: "DOP", name: "Dominican Peso", nameAr: "بيزو دومينيكي", symbol: "RD$", decimals: 2, symbolPosition: "before" },
  { code: "FJD", name: "Fijian Dollar", nameAr: "دولار فيجي", symbol: "FJ$", decimals: 2, symbolPosition: "before" },
  { code: "GEL", name: "Georgian Lari", nameAr: "لاري جورجي", symbol: "₾", decimals: 2, symbolPosition: "before" },
  { code: "GTQ", name: "Guatemalan Quetzal", nameAr: "كويتزال غواتيمالي", symbol: "Q", decimals: 2, symbolPosition: "before" },
  { code: "GYD", name: "Guyanese Dollar", nameAr: "دولار غياني", symbol: "GY$", decimals: 2, symbolPosition: "before" },
  { code: "HKD", name: "Hong Kong Dollar", nameAr: "دولار هونغ كونغ", symbol: "HK$", decimals: 2, symbolPosition: "before" },
  { code: "HNL", name: "Honduran Lempira", nameAr: "ليمبيرا هندوراسي", symbol: "L", decimals: 2, symbolPosition: "before" },
  { code: "HTG", name: "Haitian Gourde", nameAr: "غورد هايتي", symbol: "G", decimals: 2, symbolPosition: "before" },
  { code: "HUF", name: "Hungarian Forint", nameAr: "فورنت هنغاري", symbol: "Ft", decimals: 2, symbolPosition: "after" },
  { code: "IDR", name: "Indonesian Rupiah", nameAr: "روبية إندونيسية", symbol: "Rp", decimals: 0, symbolPosition: "before" },
  { code: "ILS", name: "Israeli New Shekel", nameAr: "شيكل إسرائيلي", symbol: "₪", decimals: 2, symbolPosition: "before" },
  { code: "IQD", name: "Iraqi Dinar", nameAr: "دينار عراقي", symbol: "د.ع", decimals: 3, symbolPosition: "after" },
  { code: "IRR", name: "Iranian Rial", nameAr: "ريال إيراني", symbol: "﷼", decimals: 0, symbolPosition: "after" },
  { code: "ISK", name: "Icelandic Krona", nameAr: "كرونة آيسلندية", symbol: "kr", decimals: 0, symbolPosition: "after" },
  { code: "JMD", name: "Jamaican Dollar", nameAr: "دولار جامايكي", symbol: "J$", decimals: 2, symbolPosition: "before" },
  { code: "JPY", name: "Japanese Yen", nameAr: "ين ياباني", symbol: "¥", decimals: 0, symbolPosition: "before" },
  { code: "KGS", name: "Kyrgyzstani Som", nameAr: "سوم قرغيزي", symbol: "som", decimals: 2, symbolPosition: "after" },
  { code: "KHR", name: "Cambodian Riel", nameAr: "رييل كمبودي", symbol: "៛", decimals: 2, symbolPosition: "after" },
  { code: "KPW", name: "North Korean Won", nameAr: "وون كوري شمالي", symbol: "₩", decimals: 0, symbolPosition: "before" },
  { code: "KRW", name: "South Korean Won", nameAr: "وون كوري", symbol: "₩", decimals: 0, symbolPosition: "before" },
  { code: "KZT", name: "Kazakhstani Tenge", nameAr: "تينغ كازاخستاني", symbol: "₸", decimals: 2, symbolPosition: "before" },
  { code: "LAK", name: "Lao Kip", nameAr: "كيب لاوسي", symbol: "₭", decimals: 0, symbolPosition: "after" },
  { code: "LBP", name: "Lebanese Pound", nameAr: "ليرة لبنانية", symbol: "ل.ل", decimals: 2, symbolPosition: "after" },
  { code: "SYP", name: "Syrian Pound", nameAr: "الليرة السورية", symbol: "ل.س", decimals: 2, symbolPosition: "after" },
  { code: "LKR", name: "Sri Lankan Rupee", nameAr: "روبية سريلانكية", symbol: "Rs", decimals: 2, symbolPosition: "before" },
  { code: "MDL", name: "Moldovan Leu", nameAr: "ليو مولدوفي", symbol: "L", decimals: 2, symbolPosition: "before" },
  { code: "MKD", name: "Macedonian Denar", nameAr: "دينار مقدوني", symbol: "ден", decimals: 2, symbolPosition: "after" },
  { code: "MMK", name: "Myanmar Kyat", nameAr: "كيات ميانمار", symbol: "K", decimals: 0, symbolPosition: "after" },
  { code: "MNT", name: "Mongolian Tugrik", nameAr: "توغروغ منغولي", symbol: "₮", decimals: 2, symbolPosition: "after" },
  { code: "MOP", name: "Macanese Pataca", nameAr: "باتاكا ماكاو", symbol: "MOP$", decimals: 2, symbolPosition: "before" },
  { code: "MVR", name: "Maldivian Rufiyaa", nameAr: "روفية مالديفية", symbol: "Rf", decimals: 2, symbolPosition: "before" },
  { code: "MXN", name: "Mexican Peso", nameAr: "بيزو مكسيكي", symbol: "MX$", decimals: 2, symbolPosition: "before" },
  { code: "MYR", name: "Malaysian Ringgit", nameAr: "رينغيت ماليزي", symbol: "RM", decimals: 2, symbolPosition: "before" },
  { code: "NIO", name: "Nicaraguan Córdoba", nameAr: "كوردوبا نيكاراغوي", symbol: "C$", decimals: 2, symbolPosition: "before" },
  { code: "NOK", name: "Norwegian Krone", nameAr: "كرونة نرويجية", symbol: "kr", decimals: 2, symbolPosition: "after" },
  { code: "NPR", name: "Nepalese Rupee", nameAr: "روبية نيبالية", symbol: "Rs", decimals: 2, symbolPosition: "before" },
  { code: "NZD", name: "New Zealand Dollar", nameAr: "دولار نيوزيلندي", symbol: "NZ$", decimals: 2, symbolPosition: "before" },
  { code: "PAB", name: "Panamanian Balboa", nameAr: "بالبوا بنمي", symbol: "B/", decimals: 2, symbolPosition: "before" },
  { code: "PEN", name: "Peruvian Sol", nameAr: "سول بيروفي", symbol: "S/", decimals: 2, symbolPosition: "before" },
  { code: "PGK", name: "Papua New Guinean Kina", nameAr: "كينا بابوا غينيا", symbol: "K", decimals: 2, symbolPosition: "after" },
  { code: "PHP", name: "Philippine Peso", nameAr: "بيزو فلبيني", symbol: "₱", decimals: 2, symbolPosition: "before" },
  { code: "PLN", name: "Polish Zloty", nameAr: "زلوتي بولندي", symbol: "zł", decimals: 2, symbolPosition: "after" },
  { code: "PYG", name: "Paraguayan Guarani", nameAr: "غواراني باراغواي", symbol: "₲", decimals: 0, symbolPosition: "after" },
  { code: "RON", name: "Romanian Leu", nameAr: "ليو روماني", symbol: "lei", decimals: 2, symbolPosition: "after" },
  { code: "RSD", name: "Serbian Dinar", nameAr: "دينار صربي", symbol: "RSD", decimals: 2, symbolPosition: "after" },
  { code: "RUB", name: "Russian Ruble", nameAr: "روبل روسي", symbol: "₽", decimals: 2, symbolPosition: "before" },
  { code: "SBD", name: "Solomon Islands Dollar", nameAr: "دولار جزر سليمان", symbol: "SI$", decimals: 2, symbolPosition: "before" },
  { code: "SEK", name: "Swedish Krona", nameAr: "كرونة سويدية", symbol: "kr", decimals: 2, symbolPosition: "after" },
  { code: "SGD", name: "Singapore Dollar", nameAr: "دولار سنغافوري", symbol: "S$", decimals: 2, symbolPosition: "before" },
  { code: "SRD", name: "Surinamese Dollar", nameAr: "دولار سورينامي", symbol: "SR$", decimals: 2, symbolPosition: "before" },
  { code: "THB", name: "Thai Baht", nameAr: "بات تايلندي", symbol: "฿", decimals: 2, symbolPosition: "before" },
  { code: "TJS", name: "Tajikistani Somoni", nameAr: "سوموني طاجيكي", symbol: "SM", decimals: 2, symbolPosition: "after" },
  { code: "TMT", name: "Turkmenistani Manat", nameAr: "مانات تركمانستاني", symbol: "m", decimals: 2, symbolPosition: "after" },
  { code: "TOP", name: "Tongan Paʻanga", nameAr: "بانغا تونغية", symbol: "T$", decimals: 2, symbolPosition: "before" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", nameAr: "دولار ترينيداد وتوباغو", symbol: "TT$", decimals: 2, symbolPosition: "before" },
  { code: "TWD", name: "New Taiwan Dollar", nameAr: "دولار تايواني جديد", symbol: "NT$", decimals: 2, symbolPosition: "before" },
  { code: "UAH", name: "Ukrainian Hryvnia", nameAr: "هريفنيا أوكرانية", symbol: "₴", decimals: 2, symbolPosition: "before" },
  { code: "UYU", name: "Uruguayan Peso", nameAr: "بيزو أوروغوياني", symbol: "$U", decimals: 2, symbolPosition: "before" },
  { code: "UZS", name: "Uzbekistani Som", nameAr: "سوم أوزبكستاني", symbol: "soʻm", decimals: 2, symbolPosition: "after" },
  { code: "VES", name: "Venezuelan Bolívar", nameAr: "بوليفار فنزويلي", symbol: "Bs.", decimals: 2, symbolPosition: "before" },
  { code: "VND", name: "Vietnamese Dong", nameAr: "دونغ فيتنامي", symbol: "₫", decimals: 0, symbolPosition: "before" },
  { code: "VUV", name: "Vanuatu Vatu", nameAr: "فاتو فانواتو", symbol: "VT", decimals: 0, symbolPosition: "after" },
  { code: "WST", name: "Samoan Tala", nameAr: "تالا ساموي", symbol: "T", decimals: 2, symbolPosition: "before" },
  { code: "XCD", name: "East Caribbean Dollar", nameAr: "دولار شرق الكاريبي", symbol: "EC$", decimals: 2, symbolPosition: "before" },
  { code: "YER", name: "Yemeni Rial", nameAr: "ريال يمني", symbol: "﷼", decimals: 2, symbolPosition: "after" },
];

export const COUNTRIES: readonly CountryDefinition[] = [
  { code: "SA", name: "Saudi Arabia", nameAr: "السعودية", currencyCode: "SAR", locale: "ar-SA" },
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة", currencyCode: "AED", locale: "ar-AE" },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", currencyCode: "KWD", locale: "ar-KW" },
  { code: "QA", name: "Qatar", nameAr: "قطر", currencyCode: "QAR", locale: "ar-QA" },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", currencyCode: "BHD", locale: "ar-BH" },
  { code: "OM", name: "Oman", nameAr: "عُمان", currencyCode: "OMR", locale: "ar-OM" },
  { code: "JO", name: "Jordan", nameAr: "الأردن", currencyCode: "JOD", locale: "ar-JO" },
  { code: "EG", name: "Egypt", nameAr: "مصر", currencyCode: "EGP", locale: "ar-EG" },
  { code: "MA", name: "Morocco", nameAr: "المغرب", currencyCode: "MAD", locale: "ar-MA" },
  { code: "DZ", name: "Algeria", nameAr: "الجزائر", currencyCode: "DZD", locale: "ar-DZ" },
  { code: "AO", name: "Angola", nameAr: "أنغولا", currencyCode: "AOA", locale: "pt-AO" },
  { code: "BJ", name: "Benin", nameAr: "بنين", currencyCode: "XOF", locale: "fr-BJ" },
  { code: "BW", name: "Botswana", nameAr: "بوتسوانا", currencyCode: "BWP", locale: "en-BW" },
  { code: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو", currencyCode: "XOF", locale: "fr-BF" },
  { code: "BI", name: "Burundi", nameAr: "بوروندي", currencyCode: "BIF", locale: "fr-BI" },
  { code: "CV", name: "Cabo Verde", nameAr: "الرأس الأخضر", currencyCode: "CVE", locale: "pt-CV" },
  { code: "CM", name: "Cameroon", nameAr: "الكاميرون", currencyCode: "XAF", locale: "fr-CM" },
  { code: "CF", name: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى", currencyCode: "XAF", locale: "fr-CF" },
  { code: "TD", name: "Chad", nameAr: "تشاد", currencyCode: "XAF", locale: "fr-TD" },
  { code: "KM", name: "Comoros", nameAr: "جزر القمر", currencyCode: "KMF", locale: "ar-KM" },
  { code: "CG", name: "Republic of the Congo", nameAr: "جمهورية الكونغو", currencyCode: "XAF", locale: "fr-CG" },
  { code: "CD", name: "Democratic Republic of the Congo", nameAr: "جمهورية الكونغو الديمقراطية", currencyCode: "CDF", locale: "fr-CD" },
  { code: "CI", name: "Côte d’Ivoire", nameAr: "ساحل العاج", currencyCode: "XOF", locale: "fr-CI" },
  { code: "DJ", name: "Djibouti", nameAr: "جيبوتي", currencyCode: "DJF", locale: "fr-DJ" },
  { code: "GQ", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية", currencyCode: "XAF", locale: "es-GQ" },
  { code: "ER", name: "Eritrea", nameAr: "إريتريا", currencyCode: "ERN", locale: "ar-ER" },
  { code: "SZ", name: "Eswatini", nameAr: "إسواتيني", currencyCode: "SZL", locale: "en-SZ" },
  { code: "ET", name: "Ethiopia", nameAr: "إثيوبيا", currencyCode: "ETB", locale: "am-ET" },
  { code: "GA", name: "Gabon", nameAr: "الغابون", currencyCode: "XAF", locale: "fr-GA" },
  { code: "GM", name: "The Gambia", nameAr: "غامبيا", currencyCode: "GMD", locale: "en-GM" },
  { code: "GH", name: "Ghana", nameAr: "غانا", currencyCode: "GHS", locale: "en-GH" },
  { code: "GN", name: "Guinea", nameAr: "غينيا", currencyCode: "GNF", locale: "fr-GN" },
  { code: "GW", name: "Guinea-Bissau", nameAr: "غينيا بيساو", currencyCode: "XOF", locale: "pt-GW" },
  { code: "KE", name: "Kenya", nameAr: "كينيا", currencyCode: "KES", locale: "en-KE" },
  { code: "LS", name: "Lesotho", nameAr: "ليسوتو", currencyCode: "LSL", locale: "en-LS" },
  { code: "LR", name: "Liberia", nameAr: "ليبيريا", currencyCode: "LRD", locale: "en-LR" },
  { code: "LY", name: "Libya", nameAr: "ليبيا", currencyCode: "LYD", locale: "ar-LY" },
  { code: "MG", name: "Madagascar", nameAr: "مدغشقر", currencyCode: "MGA", locale: "fr-MG" },
  { code: "MW", name: "Malawi", nameAr: "ملاوي", currencyCode: "MWK", locale: "en-MW" },
  { code: "ML", name: "Mali", nameAr: "مالي", currencyCode: "XOF", locale: "fr-ML" },
  { code: "MR", name: "Mauritania", nameAr: "موريتانيا", currencyCode: "MRU", locale: "ar-MR" },
  { code: "MU", name: "Mauritius", nameAr: "موريشيوس", currencyCode: "MUR", locale: "en-MU" },
  { code: "MZ", name: "Mozambique", nameAr: "موزمبيق", currencyCode: "MZN", locale: "pt-MZ" },
  { code: "NA", name: "Namibia", nameAr: "ناميبيا", currencyCode: "NAD", locale: "en-NA" },
  { code: "NE", name: "Niger", nameAr: "النيجر", currencyCode: "XOF", locale: "fr-NE" },
  { code: "NG", name: "Nigeria", nameAr: "نيجيريا", currencyCode: "NGN", locale: "en-NG" },
  { code: "RW", name: "Rwanda", nameAr: "رواندا", currencyCode: "RWF", locale: "rw-RW" },
  { code: "ST", name: "São Tomé and Príncipe", nameAr: "ساو تومي وبرينسيبي", currencyCode: "STN", locale: "pt-ST" },
  { code: "SC", name: "Seychelles", nameAr: "سيشل", currencyCode: "SCR", locale: "en-SC" },
  { code: "SN", name: "Senegal", nameAr: "السنغال", currencyCode: "XOF", locale: "fr-SN" },
  { code: "SL", name: "Sierra Leone", nameAr: "سيراليون", currencyCode: "SLE", locale: "en-SL" },
  { code: "SO", name: "Somalia", nameAr: "الصومال", currencyCode: "SOS", locale: "so-SO" },
  { code: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا", currencyCode: "ZAR", locale: "en-ZA" },
  { code: "SS", name: "South Sudan", nameAr: "جنوب السودان", currencyCode: "SSP", locale: "en-SS" },
  { code: "SD", name: "Sudan", nameAr: "السودان", currencyCode: "SDG", locale: "ar-SD" },
  { code: "TZ", name: "Tanzania", nameAr: "تنزانيا", currencyCode: "TZS", locale: "sw-TZ" },
  { code: "TG", name: "Togo", nameAr: "توغو", currencyCode: "XOF", locale: "fr-TG" },
  { code: "TN", name: "Tunisia", nameAr: "تونس", currencyCode: "TND", locale: "ar-TN" },
  { code: "UG", name: "Uganda", nameAr: "أوغندا", currencyCode: "UGX", locale: "en-UG" },
  { code: "ZM", name: "Zambia", nameAr: "زامبيا", currencyCode: "ZMW", locale: "en-ZM" },
  { code: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي", currencyCode: "ZWL", locale: "en-ZW" },
  { code: "TR", name: "Türkiye", nameAr: "تركيا", currencyCode: "TRY", locale: "tr-TR" },
  { code: "US", name: "United States", nameAr: "الولايات المتحدة", currencyCode: "USD", locale: "en-US" },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", currencyCode: "GBP", locale: "en-GB" },
  { code: "FR", name: "France", nameAr: "فرنسا", currencyCode: "EUR", locale: "fr-FR" },
  { code: "DE", name: "Germany", nameAr: "ألمانيا", currencyCode: "EUR", locale: "de-DE" },
  { code: "CA", name: "Canada", nameAr: "كندا", currencyCode: "CAD", locale: "en-CA" },
  { code: "AU", name: "Australia", nameAr: "أستراليا", currencyCode: "AUD", locale: "en-AU" },
  { code: "IN", name: "India", nameAr: "الهند", currencyCode: "INR", locale: "en-IN" },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", currencyCode: "PKR", locale: "ur-PK" },
  { code: "AF", name: "Afghanistan", nameAr: "أفغانستان", currencyCode: "AFN", locale: "fa-AF" },
  { code: "AL", name: "Albania", nameAr: "ألبانيا", currencyCode: "ALL", locale: "sq-AL" },
  { code: "AD", name: "Andorra", nameAr: "أندورا", currencyCode: "EUR", locale: "ca-AD" },
  { code: "AM", name: "Armenia", nameAr: "أرمينيا", currencyCode: "AMD", locale: "hy-AM" },
  { code: "AT", name: "Austria", nameAr: "النمسا", currencyCode: "EUR", locale: "de-AT" },
  { code: "AZ", name: "Azerbaijan", nameAr: "أذربيجان", currencyCode: "AZN", locale: "az-AZ" },
  { code: "BS", name: "Bahamas", nameAr: "جزر البهاما", currencyCode: "BSD", locale: "en-BS" },
  { code: "BB", name: "Barbados", nameAr: "باربادوس", currencyCode: "BBD", locale: "en-BB" },
  { code: "BY", name: "Belarus", nameAr: "بيلاروسيا", currencyCode: "BYN", locale: "be-BY" },
  { code: "BE", name: "Belgium", nameAr: "بلجيكا", currencyCode: "EUR", locale: "nl-BE" },
  { code: "BZ", name: "Belize", nameAr: "بليز", currencyCode: "BZD", locale: "en-BZ" },
  { code: "BO", name: "Bolivia", nameAr: "بوليفيا", currencyCode: "BOB", locale: "es-BO" },
  { code: "BA", name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", currencyCode: "BAM", locale: "bs-BA" },
  { code: "BR", name: "Brazil", nameAr: "البرازيل", currencyCode: "BRL", locale: "pt-BR" },
  { code: "BN", name: "Brunei", nameAr: "بروناي", currencyCode: "BND", locale: "ms-BN" },
  { code: "BG", name: "Bulgaria", nameAr: "بلغاريا", currencyCode: "BGN", locale: "bg-BG" },
  { code: "BT", name: "Bhutan", nameAr: "بوتان", currencyCode: "BTN", locale: "dz-BT" },
  { code: "KH", name: "Cambodia", nameAr: "كمبوديا", currencyCode: "KHR", locale: "km-KH" },
  { code: "CL", name: "Chile", nameAr: "تشيلي", currencyCode: "CLP", locale: "es-CL" },
  { code: "CN", name: "China", nameAr: "الصين", currencyCode: "CNY", locale: "zh-CN" },
  { code: "CO", name: "Colombia", nameAr: "كولومبيا", currencyCode: "COP", locale: "es-CO" },
  { code: "CR", name: "Costa Rica", nameAr: "كوستاريكا", currencyCode: "CRC", locale: "es-CR" },
  { code: "HR", name: "Croatia", nameAr: "كرواتيا", currencyCode: "EUR", locale: "hr-HR" },
  { code: "CU", name: "Cuba", nameAr: "كوبا", currencyCode: "CUP", locale: "es-CU" },
  { code: "CY", name: "Cyprus", nameAr: "قبرص", currencyCode: "EUR", locale: "el-CY" },
  { code: "CZ", name: "Czechia", nameAr: "التشيك", currencyCode: "CZK", locale: "cs-CZ" },
  { code: "DK", name: "Denmark", nameAr: "الدنمارك", currencyCode: "DKK", locale: "da-DK" },
  { code: "DM", name: "Dominica", nameAr: "دومينيكا", currencyCode: "XCD", locale: "en-DM" },
  { code: "DO", name: "Dominican Republic", nameAr: "جمهورية الدومينيكان", currencyCode: "DOP", locale: "es-DO" },
  { code: "EC", name: "Ecuador", nameAr: "الإكوادور", currencyCode: "USD", locale: "es-EC" },
  { code: "SV", name: "El Salvador", nameAr: "السلفادور", currencyCode: "USD", locale: "es-SV" },
  { code: "EE", name: "Estonia", nameAr: "إستونيا", currencyCode: "EUR", locale: "et-EE" },
  { code: "FJ", name: "Fiji", nameAr: "فيجي", currencyCode: "FJD", locale: "en-FJ" },
  { code: "FI", name: "Finland", nameAr: "فنلندا", currencyCode: "EUR", locale: "fi-FI" },
  { code: "GE", name: "Georgia", nameAr: "جورجيا", currencyCode: "GEL", locale: "ka-GE" },
  { code: "GR", name: "Greece", nameAr: "اليونان", currencyCode: "EUR", locale: "el-GR" },
  { code: "GD", name: "Grenada", nameAr: "غرينادا", currencyCode: "XCD", locale: "en-GD" },
  { code: "GT", name: "Guatemala", nameAr: "غواتيمالا", currencyCode: "GTQ", locale: "es-GT" },
  { code: "GY", name: "Guyana", nameAr: "غيانا", currencyCode: "GYD", locale: "en-GY" },
  { code: "HT", name: "Haiti", nameAr: "هايتي", currencyCode: "HTG", locale: "fr-HT" },
  { code: "HN", name: "Honduras", nameAr: "هندوراس", currencyCode: "HNL", locale: "es-HN" },
  { code: "HK", name: "Hong Kong", nameAr: "هونغ كونغ", currencyCode: "HKD", locale: "zh-HK" },
  { code: "HU", name: "Hungary", nameAr: "المجر", currencyCode: "HUF", locale: "hu-HU" },
  { code: "IS", name: "Iceland", nameAr: "آيسلندا", currencyCode: "ISK", locale: "is-IS" },
  { code: "ID", name: "Indonesia", nameAr: "إندونيسيا", currencyCode: "IDR", locale: "id-ID" },
  { code: "IR", name: "Iran", nameAr: "إيران", currencyCode: "IRR", locale: "fa-IR" },
  { code: "IQ", name: "Iraq", nameAr: "العراق", currencyCode: "IQD", locale: "ar-IQ" },
  { code: "IE", name: "Ireland", nameAr: "أيرلندا", currencyCode: "EUR", locale: "en-IE" },
  { code: "IL", name: "Israel", nameAr: "إسرائيل", currencyCode: "ILS", locale: "he-IL" },
  { code: "IT", name: "Italy", nameAr: "إيطاليا", currencyCode: "EUR", locale: "it-IT" },
  { code: "JM", name: "Jamaica", nameAr: "جامايكا", currencyCode: "JMD", locale: "en-JM" },
  { code: "JP", name: "Japan", nameAr: "اليابان", currencyCode: "JPY", locale: "ja-JP" },
  { code: "KZ", name: "Kazakhstan", nameAr: "كازاخستان", currencyCode: "KZT", locale: "kk-KZ" },
  { code: "KI", name: "Kiribati", nameAr: "كيريباتي", currencyCode: "AUD", locale: "en-KI" },
  { code: "KP", name: "North Korea", nameAr: "كوريا الشمالية", currencyCode: "KPW", locale: "ko-KP" },
  { code: "KR", name: "South Korea", nameAr: "كوريا الجنوبية", currencyCode: "KRW", locale: "ko-KR" },
  { code: "XK", name: "Kosovo", nameAr: "كوسوفو", currencyCode: "EUR", locale: "sq-XK" },
  { code: "KG", name: "Kyrgyzstan", nameAr: "قرغيزستان", currencyCode: "KGS", locale: "ky-KG" },
  { code: "LA", name: "Laos", nameAr: "لاوس", currencyCode: "LAK", locale: "lo-LA" },
  { code: "LV", name: "Latvia", nameAr: "لاتفيا", currencyCode: "EUR", locale: "lv-LV" },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", currencyCode: "LBP", locale: "ar-LB" },
  { code: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين", currencyCode: "CHF", locale: "de-LI" },
  { code: "LT", name: "Lithuania", nameAr: "ليتوانيا", currencyCode: "EUR", locale: "lt-LT" },
  { code: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ", currencyCode: "EUR", locale: "fr-LU" },
  { code: "MO", name: "Macao", nameAr: "ماكاو", currencyCode: "MOP", locale: "zh-MO" },
  { code: "MK", name: "North Macedonia", nameAr: "مقدونيا الشمالية", currencyCode: "MKD", locale: "mk-MK" },
  { code: "MY", name: "Malaysia", nameAr: "ماليزيا", currencyCode: "MYR", locale: "ms-MY" },
  { code: "MV", name: "Maldives", nameAr: "جزر المالديف", currencyCode: "MVR", locale: "dv-MV" },
  { code: "MT", name: "Malta", nameAr: "مالطا", currencyCode: "EUR", locale: "mt-MT" },
  { code: "MH", name: "Marshall Islands", nameAr: "جزر مارشال", currencyCode: "USD", locale: "en-MH" },
  { code: "MN", name: "Mongolia", nameAr: "منغوليا", currencyCode: "MNT", locale: "mn-MN" },
  { code: "MD", name: "Moldova", nameAr: "مولدوفا", currencyCode: "MDL", locale: "ro-MD" },
  { code: "MC", name: "Monaco", nameAr: "موناكو", currencyCode: "EUR", locale: "fr-MC" },
  { code: "ME", name: "Montenegro", nameAr: "الجبل الأسود", currencyCode: "EUR", locale: "sr-ME" },
  { code: "MM", name: "Myanmar", nameAr: "ميانمار", currencyCode: "MMK", locale: "my-MM" },
  { code: "NR", name: "Nauru", nameAr: "ناورو", currencyCode: "AUD", locale: "en-NR" },
  { code: "NP", name: "Nepal", nameAr: "نيبال", currencyCode: "NPR", locale: "ne-NP" },
  { code: "NL", name: "Netherlands", nameAr: "هولندا", currencyCode: "EUR", locale: "nl-NL" },
  { code: "NZ", name: "New Zealand", nameAr: "نيوزيلندا", currencyCode: "NZD", locale: "en-NZ" },
  { code: "NI", name: "Nicaragua", nameAr: "نيكاراغوا", currencyCode: "NIO", locale: "es-NI" },
  { code: "NO", name: "Norway", nameAr: "النرويج", currencyCode: "NOK", locale: "nb-NO" },
  { code: "PS", name: "Palestine", nameAr: "فلسطين", currencyCode: "ILS", locale: "ar-PS" },
  { code: "PA", name: "Panama", nameAr: "بنما", currencyCode: "PAB", locale: "es-PA" },
  { code: "PG", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", currencyCode: "PGK", locale: "en-PG" },
  { code: "PY", name: "Paraguay", nameAr: "باراغواي", currencyCode: "PYG", locale: "es-PY" },
  { code: "PE", name: "Peru", nameAr: "بيرو", currencyCode: "PEN", locale: "es-PE" },
  { code: "PH", name: "Philippines", nameAr: "الفلبين", currencyCode: "PHP", locale: "fil-PH" },
  { code: "PL", name: "Poland", nameAr: "بولندا", currencyCode: "PLN", locale: "pl-PL" },
  { code: "PT", name: "Portugal", nameAr: "البرتغال", currencyCode: "EUR", locale: "pt-PT" },
  { code: "PW", name: "Palau", nameAr: "بالاو", currencyCode: "USD", locale: "en-PW" },
  { code: "RO", name: "Romania", nameAr: "رومانيا", currencyCode: "RON", locale: "ro-RO" },
  { code: "RU", name: "Russia", nameAr: "روسيا", currencyCode: "RUB", locale: "ru-RU" },
  { code: "KN", name: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس", currencyCode: "XCD", locale: "en-KN" },
  { code: "LC", name: "Saint Lucia", nameAr: "سانت لوسيا", currencyCode: "XCD", locale: "en-LC" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameAr: "سانت فنسنت والغرينادين", currencyCode: "XCD", locale: "en-VC" },
  { code: "WS", name: "Samoa", nameAr: "ساموا", currencyCode: "WST", locale: "sm-WS" },
  { code: "SM", name: "San Marino", nameAr: "سان مارينو", currencyCode: "EUR", locale: "it-SM" },
  { code: "RS", name: "Serbia", nameAr: "صربيا", currencyCode: "RSD", locale: "sr-RS" },
  { code: "SG", name: "Singapore", nameAr: "سنغافورة", currencyCode: "SGD", locale: "en-SG" },
  { code: "SK", name: "Slovakia", nameAr: "سلوفاكيا", currencyCode: "EUR", locale: "sk-SK" },
  { code: "SI", name: "Slovenia", nameAr: "سلوفينيا", currencyCode: "EUR", locale: "sl-SI" },
  { code: "SB", name: "Solomon Islands", nameAr: "جزر سليمان", currencyCode: "SBD", locale: "en-SB" },
  { code: "ES", name: "Spain", nameAr: "إسبانيا", currencyCode: "EUR", locale: "es-ES" },
  { code: "LK", name: "Sri Lanka", nameAr: "سريلانكا", currencyCode: "LKR", locale: "si-LK" },
  { code: "SR", name: "Suriname", nameAr: "سورينام", currencyCode: "SRD", locale: "nl-SR" },
  { code: "SE", name: "Sweden", nameAr: "السويد", currencyCode: "SEK", locale: "sv-SE" },
  { code: "CH", name: "Switzerland", nameAr: "سويسرا", currencyCode: "CHF", locale: "de-CH" },
  { code: "SY", name: "Syria", nameAr: "سوريا", currencyCode: "SYP", locale: "ar-SY" },
  { code: "TW", name: "Taiwan", nameAr: "تايوان", currencyCode: "TWD", locale: "zh-TW" },
  { code: "TJ", name: "Tajikistan", nameAr: "طاجيكستان", currencyCode: "TJS", locale: "tg-TJ" },
  { code: "TH", name: "Thailand", nameAr: "تايلاند", currencyCode: "THB", locale: "th-TH" },
  { code: "TL", name: "Timor-Leste", nameAr: "تيمور الشرقية", currencyCode: "USD", locale: "pt-TL" },
  { code: "TO", name: "Tonga", nameAr: "تونغا", currencyCode: "TOP", locale: "to-TO" },
  { code: "TT", name: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو", currencyCode: "TTD", locale: "en-TT" },
  { code: "TM", name: "Turkmenistan", nameAr: "تركمانستان", currencyCode: "TMT", locale: "tk-TM" },
  { code: "TV", name: "Tuvalu", nameAr: "توفالو", currencyCode: "AUD", locale: "en-TV" },
  { code: "UA", name: "Ukraine", nameAr: "أوكرانيا", currencyCode: "UAH", locale: "uk-UA" },
  { code: "UY", name: "Uruguay", nameAr: "أوروغواي", currencyCode: "UYU", locale: "es-UY" },
  { code: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان", currencyCode: "UZS", locale: "uz-UZ" },
  { code: "VU", name: "Vanuatu", nameAr: "فانواتو", currencyCode: "VUV", locale: "fr-VU" },
  { code: "VA", name: "Vatican City", nameAr: "الفاتيكان", currencyCode: "EUR", locale: "it-VA" },
  { code: "VE", name: "Venezuela", nameAr: "فنزويلا", currencyCode: "VES", locale: "es-VE" },
  { code: "VN", name: "Vietnam", nameAr: "فيتنام", currencyCode: "VND", locale: "vi-VN" },
  { code: "YE", name: "Yemen", nameAr: "اليمن", currencyCode: "YER", locale: "ar-YE" },
];

export function getCurrency(code: string) {
  return CURRENCIES.find((currency) => currency.code === code) ?? CURRENCIES[0];
}

export function getCountry(code: string) {
  return COUNTRIES.find((country) => country.code === code) ?? COUNTRIES[0];
}

export function parseMoneyValue(value: number | string | null | undefined) {
  if (typeof value === "number") return Number.isFinite(value) ? value : 0;
  const raw = String(value ?? "").trim().replace(/,/g, "").replace(/[^0-9.-]/g, "");
  const unsigned = raw.replace(/(?!^)-/g, "");
  const segments = unsigned.split(".");
  const normalized = segments.length > 2
    ? segments.slice(1).every(segment => /^0+$/.test(segment))
      ? segments[0]
      : segments.join("")
    : unsigned;
  const parsed = Number(normalized);
  return Number.isFinite(parsed) ? parsed : 0;
}

export function formatMoney(value: number | string | null | undefined, currencyCode = "SAR", locale = "ar-SA") {
  const currency = getCurrency(currencyCode);
  const normalizedLocale = locale.startsWith("ar") && !locale.includes("u-nu-") ? `${locale}-u-nu-latn` : locale;
  return new Intl.NumberFormat(normalizedLocale, { minimumFractionDigits: currency.decimals, maximumFractionDigits: currency.decimals }).format(parseMoneyValue(value));
}